base_app/urls.py
from base_app import views
from django.urls import path

app_name = 'base_app'
urlpatterns = [path('', views.index_view, name='index'),
               path('medal_of_honor_detail/<int:pk>/', views.MedalOfHonorDetailView.as_view(),
                    name="medal_of_honor_detail"),
               path('medal_of_honor_list/', views.MedalOfHonorListView.as_view(), name="medal_of_honor_list"),

               path('rescue_boat_detail/<int:pk>/', views.RescueBoatDetailView.as_view(),
                    name="rescue_boat_detail"),
               path('rescue_boat_list/', views.RescueBoatListView.as_view(), name="rescue_boat_list"),

               path('rescue_station_detail/<int:pk>/', views.RescueStationDetailView.as_view(),
                    name="rescue_station_detail"),
               path('rescue_station_list/', views.RescueStationListView.as_view(), name="rescue_station_list"),

               path('rescued_boat_detail/<int:pk>/', views.RescuedBoatDetailView.as_view(),
                    name="rescued_boat_detail"),
               path('rescued_boat_list/', views.RescuedBoatListView.as_view(), name="rescued_boat_list"),

               path('rescuer_detail/<int:pk>/', views.RescuerDetailView.as_view(),
                    name="rescuer_detail"),
               path('rescuer_list/', views.RescuerListView.as_view(), name="rescuer_list"),

               path('search/', views.search_page, name="search"),

               path('rescue_detail/<int:pk>/', views.RescueDetailView.as_view(), name="rescue_detail"),
               path('rescue_list/', views.RescueListView.as_view(), name="rescue_list"),

               path('art_detail/<int:pk>/', views.ArtDetailView.as_view(), name="art_detail"),
               path('art_list/<int:pk>/', views.ArtListView.as_view(), name="art_list"),

               path('quote_detail/<int:pk>/', views.QuoteDetailView.as_view(), name="quote_detail"),
               path('quote_list/', views.QuoteListView.as_view(), name="quote_list"),

               path('create_rescuer/', views.RescuerCreateView.as_view(), name="create_rescuer")

               ]

nuit_info/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# base urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base_app.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    {% block header %}{% endblock %}
</head>
<body>
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</body>
</html>

templates/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand " href="#">{% trans 'The math saviors' %}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active contour" aria-current="page"
                       href="{% url 'base_app:index' %}">{% trans "Home" %}</a>
                </li>
            </ul>
            <form class="d-flex me-2" method="POST" action="{% url 'base_app:search' %}">{% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="{% trans 'Search' %}" name="search_query"
                       aria-label="Search">
                <button class="btn btn-outline-success" type="submit">{% trans 'Search' %}</button>
            </form>
            <form name="traduction_form" class="" action="{% url 'set_language' %}" method="post">{% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}"/>
                <select onchange="onChangeLanguage()" name="language"
                        class="form-select bg-dark text-white container pl-5">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                selected="selected"{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                    {% endfor %}
                </select>
            </form>
        </div>

    </div>
</nav>